version: "3"
services:
  flask:
    container_name: "flask"
    build: .
    ports:
        - "8050:8050"
    volumes:
      - /var/secure-api/share/web:/share
    command: >-
          python3 -m gunicorn -w 2 -b 0.0.0.0:8050 wsgi:server
    networks: 
      - main
  nginx:
    build:
      context: ./nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./etc/nginx/templates:/etc/nginx/templates:ro
      - ./etc/letsencrypt:/etc/letsencrypt:ro
      - ./certbot/data:/var/www/certbot
    networks: 
      - main
  certbot:
    container_name: certbot
    image: certbot/certbot:latest
    depends_on:
      - nginx
    command: >-
             certonly --reinstall --webroot --webroot-path=/var/www/certbot
             --email thornhill52320@gmail.com --agree-tos --no-eff-email
             -d patterned-landscapes.stephentcasey.com
    volumes:
      - ./etc/letsencrypt:/etc/letsencrypt
      - ./certbot/data:/var/www/certbot
    networks: 
      - main    
networks:
    main:
      driver: bridge    
